repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: prettier
        name: run format
        language: system
        entry: bash -c 'yarn format'
        pass_filenames: false
        types_or: [ts, javascript, scss, css, yaml, json, vue]
  - repo: local
    hooks:
      - id: lint
        name: run lint
        language: system
        entry: bash -c 'yarn lint'
        pass_filenames: false
        types_or: [ts, javascript, scss, css, yaml, json, vue]
