name: Manual Pre-Release Package Action

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Alpha version to set in package.json'
        required: true
        default: 'x.x.x-alpha.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop # Always checkout the develop branch
      - uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Update version in package.json
        run: |
          jq ".version = \"${{ inputs.version }}\"" package.json > package.json.tmp && mv package.json.tmp package.json
      - name: Commit updated package.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "Update version to ${{ inputs.version }}"
          git push origin develop # Always push to the develop branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GOVFLANDERS_NPM_TOKEN }}
      - run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          include-hidden-files: true

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop # Always checkout the develop branch
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Display folder structure
        run: ls -R
      - name: Build and publish
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: |
          echo @OnroerendErfgoed:registry=https://npm.pkg.github.com/ > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          yarn publish --tag alpha --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
